config/routes.rb
ChatAppAuth::Application.routes.draw do
  
  match 'chatroom' => 'chats#room'
  post '/new_message' => 'chats#new_message', :as => :new_message

  root :to => "public_pages#home"
  match 'signup' => 'users#new'
  match 'login' => 'sessions#new'
  match 'sessions' => 'sessions#create', :via => :post
  match 'logout' => 'sessions#destroy'
resources :users
  resources :sessions
  resources :chats

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password,:password_confirmation, :username
  has_secure_password
  validates_confirmation_of :password
  validates_presence_of :password, :on =>:create
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def room
  	redirect_to login_path unless session[:username]
  end
  def new_message
	  # Check if the message is private
	  if recipient = params[:message].match(/@(.+) (.+)/)
	    # It is private, send it to the recipient's private channel
	    @channel = "/messages/private/#{recipient.captures.first}"
	    @message = { :username => params[:username], :msg => recipient.captures.second }
	  else
	    # It's public, so send it to the public channel
	    @channel = "/messages/public"
	    @message = { :username => params[:username], :msg => params[:message] }
	  end
	 
	  respond_to do |f|
	    f.js
	  end
	end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
	#layout "home_layout"
	def home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by_username(params[:session][:username].downcase)
		if @user && @user.authenticate(params[:session][:password])
			reset_session
			session[:username] = @user.username
			flash[:notice] = "Successfully Logged in"
			redirect_to user_url(params[:session][:username])
		else
			flash.now[:notice] = "Please provide valid credentials"
			render :new
		end
    #session[:username] = params[:username]
  #render :text => "Welcome #{session[:username]}!"
  end

  def destroy
    reset_session
    flash[:notice] = "Successfully Logged out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
        reset_session
        session[:user_id] = @user.id
        flash[:notice] = "User successfully created"
        redirect_to user_url(@user.username)
    else
        render action: "new"
    end
  end

  def show
    @user = User.find_by_username(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/new_message.js.erb
// Clear message input
$('#message').val('');
 
// Send the message
<% publish_to @channel, @message %>

app/views/chats/room.html.erb
<%= subscribe_to "/messages/public" %>
<%= subscribe_to "/messages/private/#{params[:username]}" %>

<script type="text/javascript" charset="utf-8">
  PrivatePub.subscribe("/messages/public", function(data) {
    $('<p></p>').html(data.username + ": " + data.msg).appendTo('#chat_room');
  });
  
  PrivatePub.subscribe("/messages/private/<%= params[:username] %>", function(data) {
    $('<p></p>').addClass('private').html(data.username + ": " + data.msg).appendTo('#chat_room');
  });
</script>

<div class="chat_container">
  <div id="chat_room">
    <p class="alert"> Welcome to the chat room <%= session[:username] %>! </p>
  </div>
  <%=params[:username]%>
  <%= form_tag new_message_path(:username =>params[:username]), :remote => true do %>
    <%= text_field_tag :message %>
    <%= submit_tag "Send" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatAppAuth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=flash[:notice] %>

<%= yield %>
<%= params.inspect%>
</body>
</html>

app/views/public_pages/home.html.erb
<h1>Home</h1>
<p>This is the homepage.</p>
<%= link_to "Login", login_path %>
<%= link_to "Signup", signup_path %>

app/views/users/_form.html.erb
<%= form_for(@user, :html =>{:class => "form-horizontal well"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>User Information</legend>
  <fieldset>
    <div class="control-group">
      <%= f.label :username, :class=>"control-label"%>
      <div class="controls">
        <%= f.text_field :username %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class=>"control-label" %>
      <div class="controls">
        <%= f.password_field :password %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, "Confirm password",:class=>"control-label" %>
      <div class="controls">
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Save Changes", :class=>"btn btn-primary" %>
      <%= f.submit "Cancel", :class=>"btn"%>
    </div>
<%end%>

app/views/users/new.html.erb
<h1>Create Account</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1>Welcome <%=@user.username%></h1>
<%= link_to "Logout", logout_path, :method => :delete%>
<%= link_to "Join chat", chatroom_path(:username =>@user.username)%>